### ISSUE TITLE
Rendering issue with "mass_payment_cancelled" event listing

### ISSUE THREAD

**Issue by javierjulio** [Dwolla/dev-portal#305]
I believe there is an issue with the [mass payments table in the Events Overview page](https://developers.dwolla.com/api-reference/events#mass-payments) where the "mass_payment_cancelled" event is not being rendered within the table.

**Comment by spencerhunter** [comment]
Fixed, thanks @javierjulio !

**Comment by javierjulio** [comment]
You're welcome!
